/EM RUBY STRING USA O ENCONDING DE UTF-8 POR DEFAULT
*E PODE SE USAR COM ASPAS SIMPLES E COM ASPAS DUPLAS
*COM ASPAS SIMPLES NÃO DÁ PRA FAZER INTERPOLAÇÃO DE STRINGS
*E PRA FAZER ISSO USA # {STRING}
*PODE USAR ASPAS SIMPLES DENTRO DE ASPAS DUPLAS NORMAL MAS
*PARA USAR ASPAS DUPLAS DENTRO DE OUTRA ASPAS DUPLA É PRECISO
*ESCREVER ASSIM: puts " \"STRING\" "
/

puts "'simples1' \"dupla1\""
simples = 'simples2'
dupla = "dupla2"
puts "#{simples} #{dupla}"